version: "3"

networks:
  jg-net:
    driver: bridge 

services:
  cassandra:
    image: cassandra
    container_name: cassandra
    hostname: cassandra
    restart: on-failure
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9042:9042" 
      - "9160:9160"
    networks:
      - jg-net
    cap_add:
      - ALL

  elasticsearch-kibana:
    image: nshou/elasticsearch-kibana
    container_name: es-kib
    hostname: es-kib
    restart: on-failure
    ports:
      - "9200:9200"
      - "5601:5601"
    networks:
      - jg-net
    cap_add:
      - ALL

  janusgraph:
    image: iudx/janusgraph
    container_name: janusgraph
    hostname: janusgraph
    restart: on-failure
    ports:
      - "8182:8182"
    networks:
      - jg-net
    cap_add:
      - ALL
    depends_on:
      - cassandra
      - elasticsearch-kibana
    environment:
      WAIT_HOSTS: cassandra:9042, es-kib:9200
